INSERT INTO `autori`(`nome`, `cognome`, `data_nascita`, `data_morte`, `luogo_nascita`, `luogo_morte`, `vita`) VALUES (
	"Giovanni", "Verga", "1840-09-02", "1922-01-27", "Catania", "Catania", "Giovanni Carmelo Verga di Fontanabianca (Catania, 2 settembre 1840[1][2] – Catania, 27 gennaio 1922) è stato uno scrittore, drammaturgo e senatore italiano, considerato il maggior esponente della corrente letteraria del Verismo.
Di nobili natali[3], visse in un ambiente di tradizioni liberali. Si dedicò inizialmente alla scrittura di romanzi avventurosi su influsso delle opere di Dumas padre[4] e in seguito ad altri di argomento passionale tra cui Storia di una capinera che riscosse un discreto successo. Si trasferì a Firenze nel 1869 e quindi a Milano dove frequentò circoli letterari conoscendo Arrigo Boito e Giuseppe Giacosa. Con la novella Nedda si attuò la sua conversione al Verismo che lo condusse a scrivere nel 1881 la sua opera più completa I Malavoglia che con Mastro-don Gesualdo del 1889 costituiscono due fra i più notevoli romanzi della letteratura italiana.[4]
La nuova concezione verista di Verga pose il cardine dell'opera letteraria sulla 'sparizione' dell'autore, facendo in modo che nella narrazione i fatti si sviluppassero da soli, come per una necessità spontanea.[5] Il linguaggio di Verga è rude e spoglio come un riflesso del mondo che rappresenta, fatto sia di povera gente come ne I Malavoglia, sia di ricchi come in Mastro-don Gesualdo, tutti comunque dei 'vinti' nella lotta quotidiana della vita.
Lo scrittore si occupò anche di teatro, sceneggiando alcune sue novelle di cui la più famosa è Cavalleria rusticana musicata in seguito da Pietro Mascagni. Verga divenne Senatore del Regno nel 1920 su nomina del re Vittorio Emanuele III."
);

INSERT INTO `autori`(`nome`, `cognome`, `data_nascita`, `data_morte`, `luogo_nascita`, `luogo_morte`, `vita`) VALUES (
	"Giuseppe ", "Ungaretti", "1888-02-06", "1970-06-01", "Alessandria d'Egitto", "Giuseppe Ungaretti nasce a l’8 febbraio 1888 ad Alessandria d’Egitto da due lucchesi, Maria Lunardini e Antonio Ungaretti. I suoi primi anni trascorrono lì per via del lavoro del padre, che era impegnato nella costruzione del canale di Suez. Sarà proprio questo suo lavoro purtroppo che lo porterà a rimanere vittima di un incidente, per cui la madre di Ungaretti e il piccolo Giuseppe devono arrangiarsi. La donna riesce a portare avanti la famiglia grazie ai guadagni ottenuti da un negozio alla periferia di Alessandria. Giuseppe Ungaretti cresce allevato dalla mamma, da una balia sudanese e da Anna, un’anziana croata che amava raccontargli le storie.
Quando diventa grande Ungaretti entra in contatto con la letteratura europea per la prima volta grazie alla frequenza dell’Ecole Suisse Jacot e, nel tempo libero, frequenta un ritrovo internazionale di anarchici, chiamato Baracca rossa.
Nel 1912 Ungaretti vede per la prima volta l’Italia, lascia infatti l’Egitto per recarsi in Francia, dove vuole approfondire le sue nozioni di diritto, per poi fare ritorno ad Alessandria d’Egitto. A Parigi Ungaretti si iscrive infine alla Facoltà di Lettere della Sorbona e frequenta i caffè letterari più in vista di Parigi, diventando amico di Apollinaire, al quale si lega profondamente.
Anche se lontano dall’Italia, Giuseppe rimane comunque in contatto con un gruppo fiorentino, mediante il quale dà vita alla rivista Lacerba. Proprio su questa rivista Ungaretti pubblica le prime poesie coronando il suo sogno, ma sarà poco dopo questa sua prima esperienza letteraria che verrà richiamato e inviato al fronte. Ungaretti aveva infatti partecipato alla campagna interventista e si era arruolato come volontario nel 19º Reggimento di fanteria della Brigata “Brescia”; verrà quindi spedito sul Carso prima e sul fronte francese nella zona dello Champagne poi.
Il 1915 lo trascorrerà in guerra, tra retrovie e prime linee e sarà proprio durante questo periodo che scriverà alcune poesie in un taccuino, che daranno poi vita all’intera raccolta de 'Il porto sepolto', pubblicato in seguito presso una tipografia di Udine. L’opera sarà pubblicata nel 1916, mentre Ungaretti ritornerà a Parigi solo il 9 novembre del 1918 e sarà proprio nella capitale francese che troverà il suo amico Apollinaire stroncato dalla febbre spagnola.
Giuseppe rimarrà come corrispondente a Parigi, lavorando per Il Popolo d’Italia, giornale allora diretto da Benito Mussolini e nel 1919 lo troveremo impegnato come ufficio stampa presso l’ambasciata italiana.
Nel 1921 Ungaretti, insieme alla famiglia, decide di trasferirsi in Italia, nei pressi di Roma, a Marino per la precisione. Il cambiamento sarà radicale per la vita di Ungaretti, che comincerà a lavorare alla stesura del bollettino informativo quotidiano per volere del Ministero degli Esteri. Gli anni Venti del ’900 segnano la decisione del poeta di aderire al fascismo, arrivando nel 1925 a firmare il Manifesto degli intellettuali fascisti.
La sua adesione alle idee fasciste era però visibile sin dagli anni precedenti, in questo periodo infatti pubblica una nuova edizione de “L’Allegria” che include liriche composte dal 1919 al 1922 e la prefazione viene scritta da Benito Mussolini in persona. La sua poetica in questo caso ha una svolta e un cambiamento molto marcato, si esprime infatti con vocaboli più ricercati, dando vita a poesie più lunghe.
Ungaretti dovrà però aspettare il 1932 per ottenere il primo riconoscimento ufficiale alla sua poesia, quando gli verrà assegnato il Premio del gondoliere a Venezia, che gli permetterà di farsi conoscere dai grandi editori, che inizieranno a interessarsi a lui. Nel 1937 Ungaretti perde il fratello Costantino, al quale dedica le liriche 'Se tu mio fratello' e 'Tutto ho perduto'. Passa poco tempo e se ne va anche il figlio Antonietto a soli nove anni per via di un’appendicite mal curata.
In questo periodo pubblica quindi “Sentimento del tempo” con Vallecchi e il Pen Club lo invita a fare una serie di lezioni in America del Sud, dove gli viene assegnata la cattedra di Letteratura Italiana in Brasile all’Università di San Paolo, dove insegnerà fino al 1942.
Una volta rientrato dal suo viaggio in Italia (siamo nel 1942) viene nominato Accademico d’Italia ottenendo la cattedra di letteratura moderna e comparata all’università di Roma La Sapienza, cattedra che gli verrà assegnata per “chiara fama”. Nonostante i suoi meriti letterari con la caduta del fascismo Ungaretti fu sospeso dall’insegnamento, che gli fu interdetto fino al febbraio del 1947.
Mondadori, che dal 1942 aveva iniziato a pubblicare le sue opere, non interruppe l’uscita delle sue opere, iniziata con la raccolta “Vita d’un uomo”.
L’impegno del letterato per essere reintegrato nella società accademica è ben chiaro, dal momento che nel 1946 riceve da Alcide De Gasperi il premio Roma, che gli permette di far uscire il seguito del volume di prosa 'Il povero nella città' e qualche abbozzo di 'La Terra Promessa'.
Ungaretti vive gli ultimi anni della sua vita in maniera molto intensa, venendo eletto Presidente della Comunità europea degli scrittori e insegnando come visiting professor alla Columbia University. Nel 1968 entra invece in tutte le case degli italiani, grazie allo sceneggiato di Franco Rossi L’Odissea, che accompagnava ogni messa in onda con la lettura di alcuni passi del testo omerico da parte di Ungaretti.
Per i suoi 80 anni viene festeggiato in pompa magna dal governo italiano dall’allora presidente del Consiglio Aldo Moro, da Montale e Quasimodo. Di questo periodo sono le sue pubblicazioni “Dialogo” e “Morte delle stagioni”.
Il poeta continuò la sua attività e le sue pubblicazioni fino alla fine dei suoi giorni, sarà proprio durante un viaggio negli Stati Uniti, organizzato per ricevere un premio all’Università di Oklahoma , che si si ammalerà, troppo debilitato dai continui spostamenti. Tornato in Italia, si stabilirà a Salsomaggiore per curarsi, ma nulla sarà più possibile e morirà a Milano il 1° giugno 1970 per broncopolmonite all’età di 82 anni."
);

INSERT INTO `autori`(`nome`, `cognome`, `data_nascita`, `data_morte`, `luogo_nascita`, `luogo_morte`, `vita`) VALUES (
	"Luigi", "Pirandello", "1867-06-28", "1936-12-10", "Agrigento", "Roma", "1867 – 1891. Agrigento – Roma: gli studi, la laurea, le prime raccolte poetiche.
Luigi Pirandello nasce nel 1867 vicino Agrigento, in siciliano Girgenti, nella casa di campagna della contrada Caos tra Agrigento e Porto Empedocle, dove la famiglia si era rifugiata per sfuggire all’epidemia di colera che imperversava in Sicilia. La madre, Caterina Ricci Gramitto, viene da una famiglia della buona borghesia cittadina, il padre, Stefano, gestisce miniere di zolfo e la famiglia è benestante.
Fin da giovanissimo Pirandello manifesta la sua vocazione letteraria, a dodici anni scrive una tragedia, che mette in scena con le sorelle e gli amici. Nel 1880 è a Palermo dove frequenta il liceo e si iscrive alla facoltà di Lettere. In questi stessi anni si innamora della cugina Lina, che per un certo periodo è sua promessa sposa. Nel 1887 si trasferisce all’università di Roma, che abbandona nel 1889 dopo un contrasto con un professore, continua gli studi a Bonn, dove si laurea nel 1891 con una tesi sul dialetto di Agrigento. Le prime opere pubblicate, nel 1889 e 1891, sono due raccolte di versi, Mal Giocondo e Pasqua di Gea.
1891 – 1920. Roma: il matrimonio, l’allagamento delle miniere di zolfo del padre, i romanzi: L’esclusa, Il fu Mattia Pascal, I vecchi e i giovani, il saggio: L’Umorismo, Novelle per un anno e Maschere nude. 1921 – 1936. La fama internazionale e il premio Nobel, Sei personaggi in cerca d’autore, Enrico IV, Uno nessuno e centomila.
Tra il 1921 e il 1922, Pirandello scrive e mette in scena i suoi due testi teatrali più famosi Sei personaggi in cerca d’autore, prima rappresentazione a Roma nel maggio del 1921, e Enrico IV, prima rappresentazione a Milano nel febbraio del 1922. A Roma I sei personaggi scandalizzano il pubblico, l’opera è una novità sconcertante e provoca la reazione degli spettatori. A Milano, Parigi, Londra, New York il dramma ha grande successo; Pirandello lascia l’insegnamento e si dedica anima e corpo al teatro. Nel 1924, poco dopo l’assassinio Matteotti, dichiara con un testo pubblico la propria adesione al partito fascista. Negli anni successivi i rapporti dello scrittore con il fascismo saranno contraddittori; nonostante l’adesione Pirandello non nasconde il proprio disgusto e fastidio per l’Italia fascista. L’opera pirandelliana critica e complessa è lontana dall’ideologia e dalla retorica del regime fascista. L’assegnazione del Nobel a Pirandello venne letta dal regime come una contestazione della propria politica (Rapporti informativi della polizia politica. Milano, 10 novembre 1934, in G.Armellini, A. Colombo, La letteratura italiana, Zanichelli, vol.6 p.407)"
);
INSERT INTO `autori`(`nome`, `cognome`, `data_nascita`, `data_morte`, `luogo_nascita`, `luogo_morte`, `vita`) VALUES (
	"Charles", "Baudelaire", "1821-04-09", "1867-08-31", "Parigi,Francia", "Parigi,Francia", "matrimonio del padre funzionario al Senato, ormai 62enne, e della ventisettenne Caroline Archimbaut-Dufays.
In seguito alla morte del padre, la madre di Baudelaire sposa un rigido tenente colonnello che, a causa della sua freddezza e del perbenismo borghese che professa, sarà odiato dal figliastro. Baudelaire è noto per l’infelicità e il disagio esistenziale che accompagnano la sua vita, sentimenti di cui le sue opere sono intrise, e che trovano una grossa fonte proprio a partire dai rapporti dolorosi con la famiglia e, in primo luogo, con la madre.

Del rapporto con la mamma, infatti, rimangono le intense testimonianze epistolari, in cui lo si vede sempre nella costante richiesta di amore e aiuto da parte della madre. Quell’amore che Baudelaire pensa non essere mai ricambiato, quantomeno rispetto all’intensità della sua necessità dell’affetto materno come figlio.
Nel 1833 Charles, per volontà del patrigno, frequenta il Collège Royal. Le voci sulla vita dissennata e la reputazione di scavezzacollo che Baudelaire si guadagna presto, però, non tardano ad arrivare alle orecchie del patrigno che, per tutta risposta, obbliga Baudelaire a salire a bordo del Paquebot des Mers du Sud, nave diretta nelle Indie.
Questo viaggio sarà fondamentale nella cultura del poeta. In questo periodo, egli conosce altri mondi, culture diverse e molto lontane dalla decadenza mondana e culturale che l’Europa stava sperimentando in quel periodo storico. Conoscendo tante persone diverse e stando a contatto col mondo, è proprio in questo momento che Baudelaire sviluppa la sua intensa passione per l’esotismo, la stessa che trapelerà in maniera prepotente dalle pagine della sua più celebre opera, “I Fiori del male”.

Dopo soli dieci mesi sulla nave, Charles interrompe il viaggio per tornare a Parigi dove, diventato maggiorenne, può entrare in possesso dell’eredità paterna e vivere liberamente per un po’ di tempo. Nel 1842 Baudelaire conosce il grande poeta Gerard de Nerval ed è in questi anni che si avvicina a Gautier, affezzionandosi a lui in maniera quasi morbosa. La totale simbiosi tra i due porterà Baudelaire a prendere Gautier come guida sia morale che artistica.

Per quanto riguarda l’amore, la donna della vita di Charles Baudelaire è Jeanne Duval. Con lei il poeta intrattiene un’appassionata, intensa e duratura relazione d’amore, contrariamente a ciò che accadeva ai poeti a quei tempi. Il rapporto è solido e dura a lungo e Baudelaire ne trae linfa vitale; Jeanne non è solo amante, ma anche musa ispiratrice delle sue opere non solo in senso erotico e passionale ma anche per quanto riguarda quell’impronta intensamente umana che traspare dalle poesie di Baudelaire. Con il passare degli anni Jeanne starà molto vicina a Charles anche quando, con la vecchiaia, il poeta sarà colpito da paralisi.

Nel mentre, Baudelaire conduce una vita dissennata e molto dispendiosa nella bella Parigi, arrivando a sperperare metà del patrimonio lasciatogli dal padre in pochissimo tempo. Preoccupata per questo, la mamma - sotto consiglio del patrigno - assume un curatore a cui affidare il compito di gestire con maggior oculatezza il resto dell’eredità del figlio. A partire da quel momento Baudelaire dovrà chiedere soldi al curatore del suo patrimonio per qualsiasi spesa.

Tornando a parlare di letteratura, risale al 1845 l’esordio come poeta con la pubblicazione di 'A una signora creola'. Per vivere, Charles si vede costretto a collaborare con una serie di riviste e di giornali scrivendo articoli e saggi, poi raccolti in due opere postume, 'L’Arte romantica' e 'Curiosità estetiche'.
Nel 1848 Baudelaire partecipa ai moti rivoluzionari nella città di Parigi. Le cento poesie raccolte ne “I Fiori del male” vengono pubblicate nel 1857 presso l’editore Poulet-Malassis. La risposta a questo capolavoro assoluto da parte del pubblico è immediata. C’è sconcerto in merito all’opera, che fa da subito parlare di sé, più nel senso di uno scandalo che suscita morbosa curiosità che di un trionfo letterario. Proprio per via delle chiacchiere e del pettegolezzo che circonda l’opera, “I Fiori del male” viene processato per immoralità e l’editore si vede costretto a escludere sei delle poesie presenti nella raccolta.

Intanto Baudelaire è molto depresso, sconvolto nella mente, e nel 1861 tenta il suicidio. Dopo non esserci riuscito, nel 1864 di farsi ammettere all’Acadèmie francaise, il poeta si reca a Bruxelles, ma nemmeno qui riesce a trovare quiete nel suo rapporto con la società borghese. Baudelaire è malato e cerca in alcol, hashish e oppio il sollievo ai dolori dovuti alla sua patologia. Nel 1867, però, a soli 44 anni, un ictus porrà fine all’esistenza del grande autore. Proprio all’esperienza del fuggire dalla realtà in modi estremi è dedicato 'Paradisi artificiali', edito in quell’anno. Baudelaire è stato sepolto, con la madre e l’odiato patrigno, nel cimitero di Montparnasse. Risale al 1949 la riabilitazione della sua opera e delle sue memoria da parte della Corte di Cassazione francese."
);
INSERT INTO `argomenti`(`nome`, `data_inizio`, `data_fine`, `descrizione`, `luogo`) VALUES ("Prima Guerra Mondiale", "1914-07-28", "1918-11-11", "La prima guerra mondiale fu un conflitto che coinvolse le principali potenze e molte di quelle minori tra il 28 luglio 1914 e l'11 novembre 1918. Chiamata inizialmente dai contemporanei 'guerra europea', con il coinvolgimento successivo delle colonie dell'Impero britannico e di altri paesi extraeuropei, tra cui gli Stati Uniti d'America e l'Impero giapponese, prese il nome di guerra mondiale o Grande Guerra[1]: fu infatti il più grande conflitto armato mai combattuto fino alla successiva seconda guerra mondiale[2].

Il conflitto ebbe inizio il 28 luglio 1914 con la dichiarazione di guerra dell'Impero austro-ungarico al Regno di Serbia in seguito all'assassinio dell'arciduca Francesco Ferdinando, avvenuto il 28 giugno 1914 a Sarajevo per mano di Gavrilo Princip. A causa del gioco di alleanze formatesi negli ultimi decenni del XIX secolo, la guerra vide schierarsi le maggiori potenze mondiali, e le rispettive colonie, in due blocchi contrapposti: da una parte gli Imperi centrali (Impero tedesco, Impero austro-ungarico e Impero ottomano), dall'altra gli Alleati, rappresentati principalmente da Francia, Regno Unito, Impero russo, Impero giapponese e, dal 1915, Italia. Oltre 70 milioni di uomini furono mobilitati in tutto il mondo (60 milioni solo in Europa), di cui oltre 9 milioni non tornarono più a casa; si dovettero registrare anche circa 7 milioni di vittime civili, non solo per i diretti effetti delle operazioni di guerra, ma anche per le conseguenti carestie ed epidemie[3].

Le prime operazioni militari del conflitto videro la fulminea avanzata dell'esercito tedesco in Belgio e nel nord della Francia, azione fermata però dagli anglo-francesi nel corso della prima battaglia della Marna nel settembre 1914; il contemporaneo attacco dei russi da est infranse le speranze tedesche in una guerra breve e vittoriosa, e il conflitto degenerò in una logorante guerra di trincea che si replicò su tutti i fronti e perdurò fino al termine delle ostilità. A mano a mano che procedeva, la guerra raggiunse una scala mondiale con la partecipazione di molte altre nazioni, come Bulgaria, Persia, Romania, Portogallo, Brasile, Cina, Siam e Grecia; determinante per l'esito finale fu, nel 1917, l'ingresso in guerra degli Stati Uniti d'America a fianco degli Alleati.

La guerra si concluse definitivamente l'11 novembre 1918 quando la Germania, ultimo degli Imperi centrali a deporre le armi, firmò l'armistizio imposto dagli Alleati. Alcuni dei maggiori imperi esistenti al mondo – tedesco, austro-ungarico, ottomano e russo – si estinsero, generando diversi stati nazionali che ridisegnarono completamente la geografia politica dell'Europa.", "Mondo");
INSERT INTO `argomenti`(`nome`, `data_inizio`, `data_fine`, `descrizione`, `luogo`) VALUES ("Belle Epoque", "1871-06-12", "1914-12-04", "L'espressione 'Belle Époque' (Epoca Bella) nacque in Francia alla fine dell'Ottocento, scaturendo in parte dalla realtà storica e in parte da un sentimento di nostalgia. In quel periodo le invenzioni e i progressi della tecnica e della scienza furono senza paragoni con le epoche passate. Benefici di queste scoperte portarono a standard di vita notevoli e a miglioramenti sociali. L'illuminazione elettrica, la radio, l'automobile, il cinema, la pastorizzazione, e altre comodità, tutte contribuirono ad un miglioramento delle condizioni di vita e al diffondersi di un senso di ottimismo. Successivamente alla fine della guerra franco-prussiana e della grande depressione del 1873-1895, e prima della tragedia della prima guerra mondiale, la Belle Époque si colloca come un periodo di pace e relativa prosperità. Le continue scoperte e le innovazioni tecnologiche lasciavano sperare che in poco tempo si sarebbe trovata una soluzione a tutti i problemi dell'umanità. Debellata la maggior parte delle epidemie e ridotta notevolmente la mortalità infantile, alla crescita demografica fece riscontro anche un impressionante aumento della produzione industriale e del commercio mondiale, che tra il 1896 e il 1913 raddoppiarono. La sterlina britannica era il solidissimo riferimento economico.
Nel 1913 l'estensione della rete ferroviaria mondiale aveva raggiunto il milione di chilometri e le automobili cominciavano a percorrere le strade delle città americane ed europee. Il trasporto marittimo fu caratterizzato dalla corsa alla costruzione di transatlantici sempre più grandi e lussuosi (non a caso, l'affondamento del Titanic, avvenuto nel 1912, fu poi considerato come il sogno infranto della Belle Époque).
Durante questo periodo nacquero nuove forme di intrattenimento, come il cabaret, il can-can e il cinema, mentre nuove invenzioni resero la vita più facile a tutti i ceti e livelli sociali, la scena culturale prosperava e l'arte prendeva nuove forme con l'Impressionismo, il Preraffaellismo, il Simbolismo e l'Art Nouveau.

L'alta borghesia celebrava i risultati raggiunti in pochi decenni di egemonia con esposizioni universali, in cui si esibivano le ultime meraviglie della tecnica, con conferenze di esploratori, missionari e ufficiali, che raccontavano le grandezze e le miserie di mondi lontani, il cui contrasto con l'Occidente inorgogliva gli ascoltatori e confermava la loro certezza di appartenere a un mondo superiore, che nulla mai avrebbe potuto incrinare. I politici confermavano. Le guerre, se c'erano, erano lontane: in Cina, in Africa, sulle pendici dell'Himalaya.

Affrontare la vita con questo spirito significava caratterizzarlo in modo spensierato e positivo. Gli abitanti delle città avevano scoperto il piacere di uscire, anche e soprattutto dopo cena, di recarsi a chiacchierare nei caffè e assistere a spettacoli teatrali. La vita cittadina e all'interno delle città erano piene di colori: manifesti pubblicitari, vetrine con merci di ogni tipo, eleganti magazzini.
Questa mentalità e questo modo di affrontare la vita aveva condizionato anche i settori produttivi. In tutta Europa si erano sviluppate una serie di correnti artistiche giunte a teorizzare che ogni produzione umana poteva divenire un'espressione artistica. Ogni oggetto e ogni luogo diveniva un'elegante decorazione, un motivo floreale, una linea curva e arabesca.
Quando iniziò il nuovo secolo, Parigi volle celebrarlo con un'incredibile mostra nella quale venivano esposte le innovazioni più recenti: l'esposizione universale (o Exposition Universelle). Nel 1900 persone da tutto il mondo sbarcarono in Francia per assistere alla gigantesca fiera. La gente ne visitava ogni parte e ne ammirava tutti gli aspetti, dalle scale mobili (dette 'tapis roulant') ai tram elettrici, assaggiando le cento varietà di tè importato dall'India.

L'Europa era in pace da trent'anni (circa dal 1870), cioè da quando la Germania aveva inaugurato un'industrializzazione e sviluppo che venivano garantite dalla nuova politica di equilibrio. Nessuno pensava più, quindi, che la guerra potesse devastare ancora il mondo; nel 1894 ebbe perciò luogo anche il primo congresso sui giochi olimpici, che stabilì che le Olimpiadi si sarebbero svolte ogni 4 anni.