INSERT INTO `autori`(`nome`, `cognome`, `data_nascita`, `data_morte`, `luogo_nascita`, `luogo_morte`, `vita`) VALUES (
	"Giovanni", "Verga", "1840-09-02", "1922-01-27", "Catania", "Catania", "Giovanni Carmelo Verga di Fontanabianca (Catania, 2 settembre 1840[1][2] – Catania, 27 gennaio 1922) è stato uno scrittore, drammaturgo e senatore italiano, considerato il maggior esponente della corrente letteraria del Verismo.

Di nobili natali[3], visse in un ambiente di tradizioni liberali. Si dedicò inizialmente alla scrittura di romanzi avventurosi su influsso delle opere di Dumas padre[4] e in seguito ad altri di argomento passionale tra cui Storia di una capinera che riscosse un discreto successo. Si trasferì a Firenze nel 1869 e quindi a Milano dove frequentò circoli letterari conoscendo Arrigo Boito e Giuseppe Giacosa. Con la novella Nedda si attuò la sua conversione al Verismo che lo condusse a scrivere nel 1881 la sua opera più completa I Malavoglia che con Mastro-don Gesualdo del 1889 costituiscono due fra i più notevoli romanzi della letteratura italiana.[4]

La nuova concezione verista di Verga pose il cardine dell'opera letteraria sulla 'sparizione' dell'autore, facendo in modo che nella narrazione i fatti si sviluppassero da soli, come per una necessità spontanea.[5] Il linguaggio di Verga è rude e spoglio come un riflesso del mondo che rappresenta, fatto sia di povera gente come ne I Malavoglia, sia di ricchi come in Mastro-don Gesualdo, tutti comunque dei 'vinti' nella lotta quotidiana della vita.

Lo scrittore si occupò anche di teatro, sceneggiando alcune sue novelle di cui la più famosa è Cavalleria rusticana musicata in seguito da Pietro Mascagni. Verga divenne Senatore del Regno nel 1920 su nomina del re Vittorio Emanuele III."
);

INSERT INTO `argomenti`(`nome`, `data_inizio`, `data_fine`, `descrizione`, `luogo`) VALUES ("Prima Guerra Mondiale", "1914-07-28", "1918-11-11", "La prima guerra mondiale fu un conflitto che coinvolse le principali potenze e molte di quelle minori tra il 28 luglio 1914 e l'11 novembre 1918. Chiamata inizialmente dai contemporanei 'guerra europea', con il coinvolgimento successivo delle colonie dell'Impero britannico e di altri paesi extraeuropei, tra cui gli Stati Uniti d'America e l'Impero giapponese, prese il nome di guerra mondiale o Grande Guerra[1]: fu infatti il più grande conflitto armato mai combattuto fino alla successiva seconda guerra mondiale[2].

Il conflitto ebbe inizio il 28 luglio 1914 con la dichiarazione di guerra dell'Impero austro-ungarico al Regno di Serbia in seguito all'assassinio dell'arciduca Francesco Ferdinando, avvenuto il 28 giugno 1914 a Sarajevo per mano di Gavrilo Princip. A causa del gioco di alleanze formatesi negli ultimi decenni del XIX secolo, la guerra vide schierarsi le maggiori potenze mondiali, e le rispettive colonie, in due blocchi contrapposti: da una parte gli Imperi centrali (Impero tedesco, Impero austro-ungarico e Impero ottomano), dall'altra gli Alleati, rappresentati principalmente da Francia, Regno Unito, Impero russo, Impero giapponese e, dal 1915, Italia. Oltre 70 milioni di uomini furono mobilitati in tutto il mondo (60 milioni solo in Europa), di cui oltre 9 milioni non tornarono più a casa; si dovettero registrare anche circa 7 milioni di vittime civili, non solo per i diretti effetti delle operazioni di guerra, ma anche per le conseguenti carestie ed epidemie[3].

Le prime operazioni militari del conflitto videro la fulminea avanzata dell'esercito tedesco in Belgio e nel nord della Francia, azione fermata però dagli anglo-francesi nel corso della prima battaglia della Marna nel settembre 1914; il contemporaneo attacco dei russi da est infranse le speranze tedesche in una guerra breve e vittoriosa, e il conflitto degenerò in una logorante guerra di trincea che si replicò su tutti i fronti e perdurò fino al termine delle ostilità. A mano a mano che procedeva, la guerra raggiunse una scala mondiale con la partecipazione di molte altre nazioni, come Bulgaria, Persia, Romania, Portogallo, Brasile, Cina, Siam e Grecia; determinante per l'esito finale fu, nel 1917, l'ingresso in guerra degli Stati Uniti d'America a fianco degli Alleati.

La guerra si concluse definitivamente l'11 novembre 1918 quando la Germania, ultimo degli Imperi centrali a deporre le armi, firmò l'armistizio imposto dagli Alleati. Alcuni dei maggiori imperi esistenti al mondo – tedesco, austro-ungarico, ottomano e russo – si estinsero, generando diversi stati nazionali che ridisegnarono completamente la geografia politica dell'Europa.", "Mondo");